insert into users (user_id,username, password) values (1,'vleathley0@fastcompany.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (2,'gmilesop1@house.gov', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (3,'ggullefant2@princeton.edu', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (4,'wvanmerwe3@ihg.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (5,'abawdon4@themeforest.net', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (6,'kjeenes5@mlb.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (7,'earrow6@hao123.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (8,'acretney7@businessinsider.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (9,'bcoffey8@cmu.edu', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (10,'swilkie9@digg.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (11,'kgriswooda@aol.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (12,'nlustedb@skyrock.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (13,'gbaistowc@last.fm', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (14,'ecomberbeachd@netlog.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (15,'mstonmane@flickr.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (16,'ddumbaref@theguardian.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (17,'cjancicg@mtv.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (18,'cphidginh@amazonaws.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (19,'stomaszczyki@themeforest.net', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (20,'blistj@oracle.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (21,'cparsandk@dmoz.org', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (22,'otitfordl@etsy.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (23,'lyeatmanm@amazon.co.jp', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (24,'bconersn@w3.org', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (25,'mvarrowo@imdb.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (26,'egattyp@umn.edu', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (27,'eduboisq@unesco.org', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (28,'apumfreyr@theglobeandmail.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (29,'gbusseys@canalblog.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');
insert into users (user_id,username, password) values (30,'kellert@cbsnews.com', '$2a$12$FaBXJTWe5H3mWGckmh2tYuUn62xSqk1Bw4nZ3PL.sWVFJd5wv.FTa');

INSERT INTO roles(name) VALUES('FARMACY_ADMIN');
INSERT INTO roles(name) VALUES('SYS_ADMIN');
INSERT INTO roles(name) VALUES('PATIENT');

insert into USER_ROLES(user_id, role_id) values(1, 1);
insert into USER_ROLES(user_id, role_id) values(1, 2);
insert into USER_ROLES(user_id, role_id) values(1, 3);
insert into USER_ROLES(user_id, role_id) values(2, 2);
insert into USER_ROLES(user_id, role_id) values(3, 3);
